### ISSUE TITLE
Enhancement: add possibility to delete your account

### ISSUE THREAD

**Issue by sazik** [Ioni14/fleet-manager-api#23]
...and saved data

**Comment by Ioni14** [comment]
Since the production took fire... All the accounts and data have been deleted.
We are currently reworking Fleet Manager and we are switching to Auth0 for Authentication, we won't store any user information, only Star Citizen data you give.
Don't worry, we add back the delete feature soon, we just have to deal with Auth0. So, I don't close this issue yet.

**Comment by Ioni14** [comment]
Done in API side. Soon integrated in SPA side.

https://github.com/Ioni14/fleet-manager-api/pull/44
